// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2VjZ9nSI42IAHBElPhDg2yZ24TUMP-Y',
    appId: '1:361385379289:web:9651675311b1f863dc45c8',
    messagingSenderId: '361385379289',
    projectId: 'farmers-market-c591f',
    authDomain: 'farmers-market-c591f.firebaseapp.com',
    storageBucket: 'farmers-market-c591f.firebasestorage.app',
    measurementId: 'G-TSLCLXBMM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5K4VkwDggWxiqsr07kywj7IRplK48Tc',
    appId: '1:361385379289:android:52cab9bbb5901857dc45c8',
    messagingSenderId: '361385379289',
    projectId: 'farmers-market-c591f',
    storageBucket: 'farmers-market-c591f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN2OZb1dg5OwnxrK-QsP6XBuiyC9fsF4U',
    appId: '1:361385379289:ios:baf196b808ac1392dc45c8',
    messagingSenderId: '361385379289',
    projectId: 'farmers-market-c591f',
    storageBucket: 'farmers-market-c591f.firebasestorage.app',
    iosBundleId: 'com.sp.groceries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN2OZb1dg5OwnxrK-QsP6XBuiyC9fsF4U',
    appId: '1:361385379289:ios:baf196b808ac1392dc45c8',
    messagingSenderId: '361385379289',
    projectId: 'farmers-market-c591f',
    storageBucket: 'farmers-market-c591f.firebasestorage.app',
    iosBundleId: 'com.sp.groceries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg2VjZ9nSI42IAHBElPhDg2yZ24TUMP-Y',
    appId: '1:361385379289:web:4f171ac1bebc2292dc45c8',
    messagingSenderId: '361385379289',
    projectId: 'farmers-market-c591f',
    authDomain: 'farmers-market-c591f.firebaseapp.com',
    storageBucket: 'farmers-market-c591f.firebasestorage.app',
    measurementId: 'G-RTLBRHL3DD',
  );
}
